"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ohvcv_price import OHVCVPrice
globals()['OHVCVPrice'] = OHVCVPrice
from openapi_client.model.ohvcv_prices import OHVCVPrices


class TestOHVCVPrices(unittest.TestCase):
    """OHVCVPrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOHVCVPrices(self):
        """Test OHVCVPrices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OHVCVPrices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
