"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.company_valuation_api import CompanyValuationApi  # noqa: E501


class TestCompanyValuationApi(unittest.TestCase):
    """CompanyValuationApi unit test stubs"""

    def setUp(self):
        self.api = CompanyValuationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_profile(self):
        """Test case for profile

        Get the Company profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
