"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.end_of_day_price import EndOfDayPrice
globals()['EndOfDayPrice'] = EndOfDayPrice
from openapi_client.model.end_of_day_price_history import EndOfDayPriceHistory


class TestEndOfDayPriceHistory(unittest.TestCase):
    """EndOfDayPriceHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndOfDayPriceHistory(self):
        """Test EndOfDayPriceHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndOfDayPriceHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
