"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.end_of_day_price import EndOfDayPrice


class TestEndOfDayPrice(unittest.TestCase):
    """EndOfDayPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndOfDayPrice(self):
        """Test EndOfDayPrice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndOfDayPrice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
