"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.history_api import HistoryApi  # noqa: E501


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self):
        self.api = HistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_daily_prices(self):
        """Test case for daily_prices

        Get Ticker price  # noqa: E501
        """
        pass

    def test_intra_day_prices(self):
        """Test case for intra_day_prices

        Get Ticker price  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
