"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.company_quote import CompanyQuote


class TestCompanyQuote(unittest.TestCase):
    """CompanyQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyQuote(self):
        """Test CompanyQuote"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompanyQuote()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
