"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.list_api import ListApi  # noqa: E501


class TestListApi(unittest.TestCase):
    """ListApi unit test stubs"""

    def setUp(self):
        self.api = ListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_symbols(self):
        """Test case for list_symbols

        Get list of symbols  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
