"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class CompanyProfile(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'symbol': (str,),  # noqa: E501
            'price': (float,),  # noqa: E501
            'company_name': (str,),  # noqa: E501
            'currency': (str,),  # noqa: E501
            'exchange': (str,),  # noqa: E501
            'exchange_short_name': (str,),  # noqa: E501
            'industry': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'sector': (str,),  # noqa: E501
            'beta': (float,),  # noqa: E501
            'vol_avg': (float,),  # noqa: E501
            'mkt_cap': (float,),  # noqa: E501
            'last_div': (float,),  # noqa: E501
            'range': (str,),  # noqa: E501
            'changes': (float,),  # noqa: E501
            'isin': (str,),  # noqa: E501
            'cusip': (str,),  # noqa: E501
            'website': (str,),  # noqa: E501
            'ceo': (str,),  # noqa: E501
            'country': (str,),  # noqa: E501
            'full_time_employees': (float,),  # noqa: E501
            'phone': (str,),  # noqa: E501
            'address': (str,),  # noqa: E501
            'city': (str,),  # noqa: E501
            'state': (str,),  # noqa: E501
            'zip': (str,),  # noqa: E501
            'dcf_diff': (float,),  # noqa: E501
            'dcf': (float,),  # noqa: E501
            'image': (str,),  # noqa: E501
            'ipo_date': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'symbol': 'symbol',  # noqa: E501
        'price': 'price',  # noqa: E501
        'company_name': 'companyName',  # noqa: E501
        'currency': 'currency',  # noqa: E501
        'exchange': 'exchange',  # noqa: E501
        'exchange_short_name': 'exchangeShortName',  # noqa: E501
        'industry': 'industry',  # noqa: E501
        'description': 'description',  # noqa: E501
        'sector': 'sector',  # noqa: E501
        'beta': 'beta',  # noqa: E501
        'vol_avg': 'volAvg',  # noqa: E501
        'mkt_cap': 'mktCap',  # noqa: E501
        'last_div': 'lastDiv',  # noqa: E501
        'range': 'range',  # noqa: E501
        'changes': 'changes',  # noqa: E501
        'isin': 'isin',  # noqa: E501
        'cusip': 'cusip',  # noqa: E501
        'website': 'website',  # noqa: E501
        'ceo': 'ceo',  # noqa: E501
        'country': 'country',  # noqa: E501
        'full_time_employees': 'fullTimeEmployees',  # noqa: E501
        'phone': 'phone',  # noqa: E501
        'address': 'address',  # noqa: E501
        'city': 'city',  # noqa: E501
        'state': 'state',  # noqa: E501
        'zip': 'zip',  # noqa: E501
        'dcf_diff': 'dcfDiff',  # noqa: E501
        'dcf': 'dcf',  # noqa: E501
        'image': 'image',  # noqa: E501
        'ipo_date': 'ipoDate',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, symbol, price, company_name, currency, exchange, exchange_short_name, industry, description, sector, *args, **kwargs):  # noqa: E501
        """CompanyProfile - a model defined in OpenAPI

        Args:
            symbol (str):
            price (float):
            company_name (str):
            currency (str):
            exchange (str):
            exchange_short_name (str):
            industry (str):
            description (str):
            sector (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            beta (float): [optional]  # noqa: E501
            vol_avg (float): [optional]  # noqa: E501
            mkt_cap (float): [optional]  # noqa: E501
            last_div (float): [optional]  # noqa: E501
            range (str): [optional]  # noqa: E501
            changes (float): [optional]  # noqa: E501
            isin (str): [optional]  # noqa: E501
            cusip (str): [optional]  # noqa: E501
            website (str): [optional]  # noqa: E501
            ceo (str): [optional]  # noqa: E501
            country (str): [optional]  # noqa: E501
            full_time_employees (float): [optional]  # noqa: E501
            phone (str): [optional]  # noqa: E501
            address (str): [optional]  # noqa: E501
            city (str): [optional]  # noqa: E501
            state (str): [optional]  # noqa: E501
            zip (str): [optional]  # noqa: E501
            dcf_diff (float): [optional]  # noqa: E501
            dcf (float): [optional]  # noqa: E501
            image (str): [optional]  # noqa: E501
            ipo_date (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.symbol = symbol
        self.price = price
        self.company_name = company_name
        self.currency = currency
        self.exchange = exchange
        self.exchange_short_name = exchange_short_name
        self.industry = industry
        self.description = description
        self.sector = sector
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
