"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.end_of_day_price_history import EndOfDayPriceHistory
from openapi_client.model.ohvcv_prices import OHVCVPrices


class HistoryApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __daily_prices(
            self,
            symbol,
            **kwargs
        ):
            """Get Ticker price  # noqa: E501

              # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.daily_prices(symbol, async_req=True)
            >>> result = thread.get()

            Args:
                symbol (str): Name of ticker

            Keyword Args:
                _from (date): From date. [optional]
                to (date): To date. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                EndOfDayPriceHistory
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['symbol'] = \
                symbol
            return self.call_with_http_info(**kwargs)

        self.daily_prices = _Endpoint(
            settings={
                'response_type': (EndOfDayPriceHistory,),
                'auth': [
                    'api_key'
                ],
                'endpoint_path': '/historical-price-full/{symbol}',
                'operation_id': 'daily_prices',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'symbol',
                    '_from',
                    'to',
                ],
                'required': [
                    'symbol',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'symbol':
                        (str,),
                    '_from':
                        (date,),
                    'to':
                        (date,),
                },
                'attribute_map': {
                    'symbol': 'symbol',
                    '_from': 'from',
                    'to': 'to',
                },
                'location_map': {
                    'symbol': 'path',
                    '_from': 'query',
                    'to': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__daily_prices
        )

        def __intra_day_prices(
            self,
            symbol,
            resolution,
            **kwargs
        ):
            """Get Ticker price  # noqa: E501

              # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.intra_day_prices(symbol, resolution, async_req=True)
            >>> result = thread.get()

            Args:
                symbol (str): Name of ticker
                resolution (str): Time resolution

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                OHVCVPrices
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['symbol'] = \
                symbol
            kwargs['resolution'] = \
                resolution
            return self.call_with_http_info(**kwargs)

        self.intra_day_prices = _Endpoint(
            settings={
                'response_type': (OHVCVPrices,),
                'auth': [
                    'api_key'
                ],
                'endpoint_path': '/historical-chart/{resolution}/{symbol}',
                'operation_id': 'intra_day_prices',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'symbol',
                    'resolution',
                ],
                'required': [
                    'symbol',
                    'resolution',
                ],
                'nullable': [
                ],
                'enum': [
                    'resolution',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('resolution',): {

                        "1MIN": "1min",
                        "5MIN": "5min",
                        "15MIN": "15min",
                        "30MIN": "30min",
                        "1HOUR": "1hour",
                        "4HOUR": "4hour"
                    },
                },
                'openapi_types': {
                    'symbol':
                        (str,),
                    'resolution':
                        (str,),
                },
                'attribute_map': {
                    'symbol': 'symbol',
                    'resolution': 'resolution',
                },
                'location_map': {
                    'symbol': 'path',
                    'resolution': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__intra_day_prices
        )
