"""
    Financial Modeling Prep API

    Financial Modeling Prep API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Financial Modeling Prep API",
    author="OpenAPI Generator community",
    author_email="sam@sddproductions.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Financial Modeling Prep API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="GPL-3.0",
    long_description="""\
    Financial Modeling Prep API  # noqa: E501
    """
)
